server:
  port: 8080
  servlet:
    context-path:
spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:./src/main/resources/papyri;MODE=PostgreSQL
    username: sa
    password:
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: false
upload:
    path: src\\main\\resources\\pictures\\
    maxPictureWidth: 10000
    maxPictureHeight: 50000
    maxFragmentWidth: 5000
    maxFragmentHeight: 5000
